Started at Fri Nov 15 05:37:55 CET 2024
Processing corruption type: gaussian_noise
Traceback (most recent call last):
  File "tools/test.py", line 123, in <module>
    main()
  File "tools/test.py", line 86, in main
    cfg = Config.fromfile(args.config)
  File "/pfs/work7/workspace/scratch/ma_mkacar-team_project_fss2024/miniconda3/envs/py310/lib/python3.8/site-packages/mmengine/config/config.py", line 461, in fromfile
    cfg_dict, cfg_text, env_variables = Config._file2dict(
  File "/pfs/work7/workspace/scratch/ma_mkacar-team_project_fss2024/miniconda3/envs/py310/lib/python3.8/site-packages/mmengine/config/config.py", line 947, in _file2dict
    raise e
  File "/pfs/work7/workspace/scratch/ma_mkacar-team_project_fss2024/miniconda3/envs/py310/lib/python3.8/site-packages/mmengine/config/config.py", line 889, in _file2dict
    _cfg_dict, _cfg_text, _env_variables = Config._file2dict(
  File "/pfs/work7/workspace/scratch/ma_mkacar-team_project_fss2024/miniconda3/envs/py310/lib/python3.8/site-packages/mmengine/config/config.py", line 947, in _file2dict
    raise e
  File "/pfs/work7/workspace/scratch/ma_mkacar-team_project_fss2024/miniconda3/envs/py310/lib/python3.8/site-packages/mmengine/config/config.py", line 889, in _file2dict
    _cfg_dict, _cfg_text, _env_variables = Config._file2dict(
  File "/pfs/work7/workspace/scratch/ma_mkacar-team_project_fss2024/miniconda3/envs/py310/lib/python3.8/site-packages/mmengine/config/config.py", line 845, in _file2dict
    if lazy_import is None and Config._is_lazy_import(filename):
  File "/pfs/work7/workspace/scratch/ma_mkacar-team_project_fss2024/miniconda3/envs/py310/lib/python3.8/site-packages/mmengine/config/config.py", line 1661, in _is_lazy_import
    with open(filename, encoding='utf-8') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/pfs/work7/workspace/scratch/ma_mkacar-team_project_fss2024/benchmarking_robustness/semantic_segmentation/corruptions/corruption_config/pascalvoc/mask2former/./mask2former_r50_8xb2-160k_voc12aug-512x512.py'
Finished processing corruption type: gaussian_noise
Processing corruption type: shot_noise
Traceback (most recent call last):
  File "tools/test.py", line 123, in <module>
    main()
  File "tools/test.py", line 86, in main
    cfg = Config.fromfile(args.config)
  File "/pfs/work7/workspace/scratch/ma_mkacar-team_project_fss2024/miniconda3/envs/py310/lib/python3.8/site-packages/mmengine/config/config.py", line 461, in fromfile
    cfg_dict, cfg_text, env_variables = Config._file2dict(
  File "/pfs/work7/workspace/scratch/ma_mkacar-team_project_fss2024/miniconda3/envs/py310/lib/python3.8/site-packages/mmengine/config/config.py", line 947, in _file2dict
    raise e
  File "/pfs/work7/workspace/scratch/ma_mkacar-team_project_fss2024/miniconda3/envs/py310/lib/python3.8/site-packages/mmengine/config/config.py", line 889, in _file2dict
    _cfg_dict, _cfg_text, _env_variables = Config._file2dict(
  File "/pfs/work7/workspace/scratch/ma_mkacar-team_project_fss2024/miniconda3/envs/py310/lib/python3.8/site-packages/mmengine/config/config.py", line 947, in _file2dict
    raise e
  File "/pfs/work7/workspace/scratch/ma_mkacar-team_project_fss2024/miniconda3/envs/py310/lib/python3.8/site-packages/mmengine/config/config.py", line 889, in _file2dict
    _cfg_dict, _cfg_text, _env_variables = Config._file2dict(
  File "/pfs/work7/workspace/scratch/ma_mkacar-team_project_fss2024/miniconda3/envs/py310/lib/python3.8/site-packages/mmengine/config/config.py", line 845, in _file2dict
    if lazy_import is None and Config._is_lazy_import(filename):
  File "/pfs/work7/workspace/scratch/ma_mkacar-team_project_fss2024/miniconda3/envs/py310/lib/python3.8/site-packages/mmengine/config/config.py", line 1661, in _is_lazy_import
    with open(filename, encoding='utf-8') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/pfs/work7/workspace/scratch/ma_mkacar-team_project_fss2024/benchmarking_robustness/semantic_segmentation/corruptions/corruption_config/pascalvoc/mask2former/./mask2former_r50_8xb2-160k_voc12aug-512x512.py'
Finished processing corruption type: shot_noise
Processing corruption type: impulse_noise
Traceback (most recent call last):
  File "tools/test.py", line 123, in <module>
    main()
  File "tools/test.py", line 86, in main
    cfg = Config.fromfile(args.config)
  File "/pfs/work7/workspace/scratch/ma_mkacar-team_project_fss2024/miniconda3/envs/py310/lib/python3.8/site-packages/mmengine/config/config.py", line 461, in fromfile
    cfg_dict, cfg_text, env_variables = Config._file2dict(
  File "/pfs/work7/workspace/scratch/ma_mkacar-team_project_fss2024/miniconda3/envs/py310/lib/python3.8/site-packages/mmengine/config/config.py", line 947, in _file2dict
    raise e
  File "/pfs/work7/workspace/scratch/ma_mkacar-team_project_fss2024/miniconda3/envs/py310/lib/python3.8/site-packages/mmengine/config/config.py", line 889, in _file2dict
    _cfg_dict, _cfg_text, _env_variables = Config._file2dict(
  File "/pfs/work7/workspace/scratch/ma_mkacar-team_project_fss2024/miniconda3/envs/py310/lib/python3.8/site-packages/mmengine/config/config.py", line 947, in _file2dict
    raise e
  File "/pfs/work7/workspace/scratch/ma_mkacar-team_project_fss2024/miniconda3/envs/py310/lib/python3.8/site-packages/mmengine/config/config.py", line 889, in _file2dict
    _cfg_dict, _cfg_text, _env_variables = Config._file2dict(
  File "/pfs/work7/workspace/scratch/ma_mkacar-team_project_fss2024/miniconda3/envs/py310/lib/python3.8/site-packages/mmengine/config/config.py", line 845, in _file2dict
    if lazy_import is None and Config._is_lazy_import(filename):
  File "/pfs/work7/workspace/scratch/ma_mkacar-team_project_fss2024/miniconda3/envs/py310/lib/python3.8/site-packages/mmengine/config/config.py", line 1661, in _is_lazy_import
    with open(filename, encoding='utf-8') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/pfs/work7/workspace/scratch/ma_mkacar-team_project_fss2024/benchmarking_robustness/semantic_segmentation/corruptions/corruption_config/pascalvoc/mask2former/./mask2former_r50_8xb2-160k_voc12aug-512x512.py'
Finished processing corruption type: impulse_noise
Processing corruption type: defocus_blur
Traceback (most recent call last):
  File "tools/test.py", line 123, in <module>
    main()
  File "tools/test.py", line 86, in main
    cfg = Config.fromfile(args.config)
  File "/pfs/work7/workspace/scratch/ma_mkacar-team_project_fss2024/miniconda3/envs/py310/lib/python3.8/site-packages/mmengine/config/config.py", line 461, in fromfile
    cfg_dict, cfg_text, env_variables = Config._file2dict(
  File "/pfs/work7/workspace/scratch/ma_mkacar-team_project_fss2024/miniconda3/envs/py310/lib/python3.8/site-packages/mmengine/config/config.py", line 947, in _file2dict
    raise e
  File "/pfs/work7/workspace/scratch/ma_mkacar-team_project_fss2024/miniconda3/envs/py310/lib/python3.8/site-packages/mmengine/config/config.py", line 889, in _file2dict
    _cfg_dict, _cfg_text, _env_variables = Config._file2dict(
  File "/pfs/work7/workspace/scratch/ma_mkacar-team_project_fss2024/miniconda3/envs/py310/lib/python3.8/site-packages/mmengine/config/config.py", line 947, in _file2dict
    raise e
  File "/pfs/work7/workspace/scratch/ma_mkacar-team_project_fss2024/miniconda3/envs/py310/lib/python3.8/site-packages/mmengine/config/config.py", line 889, in _file2dict
    _cfg_dict, _cfg_text, _env_variables = Config._file2dict(
  File "/pfs/work7/workspace/scratch/ma_mkacar-team_project_fss2024/miniconda3/envs/py310/lib/python3.8/site-packages/mmengine/config/config.py", line 845, in _file2dict
    if lazy_import is None and Config._is_lazy_import(filename):
  File "/pfs/work7/workspace/scratch/ma_mkacar-team_project_fss2024/miniconda3/envs/py310/lib/python3.8/site-packages/mmengine/config/config.py", line 1661, in _is_lazy_import
    with open(filename, encoding='utf-8') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/pfs/work7/workspace/scratch/ma_mkacar-team_project_fss2024/benchmarking_robustness/semantic_segmentation/corruptions/corruption_config/pascalvoc/mask2former/./mask2former_r50_8xb2-160k_voc12aug-512x512.py'
Finished processing corruption type: defocus_blur
Processing corruption type: glass_blur
Traceback (most recent call last):
  File "tools/test.py", line 123, in <module>
    main()
  File "tools/test.py", line 86, in main
    cfg = Config.fromfile(args.config)
  File "/pfs/work7/workspace/scratch/ma_mkacar-team_project_fss2024/miniconda3/envs/py310/lib/python3.8/site-packages/mmengine/config/config.py", line 461, in fromfile
    cfg_dict, cfg_text, env_variables = Config._file2dict(
  File "/pfs/work7/workspace/scratch/ma_mkacar-team_project_fss2024/miniconda3/envs/py310/lib/python3.8/site-packages/mmengine/config/config.py", line 947, in _file2dict
    raise e
  File "/pfs/work7/workspace/scratch/ma_mkacar-team_project_fss2024/miniconda3/envs/py310/lib/python3.8/site-packages/mmengine/config/config.py", line 889, in _file2dict
    _cfg_dict, _cfg_text, _env_variables = Config._file2dict(
  File "/pfs/work7/workspace/scratch/ma_mkacar-team_project_fss2024/miniconda3/envs/py310/lib/python3.8/site-packages/mmengine/config/config.py", line 947, in _file2dict
    raise e
  File "/pfs/work7/workspace/scratch/ma_mkacar-team_project_fss2024/miniconda3/envs/py310/lib/python3.8/site-packages/mmengine/config/config.py", line 889, in _file2dict
    _cfg_dict, _cfg_text, _env_variables = Config._file2dict(
  File "/pfs/work7/workspace/scratch/ma_mkacar-team_project_fss2024/miniconda3/envs/py310/lib/python3.8/site-packages/mmengine/config/config.py", line 845, in _file2dict
    if lazy_import is None and Config._is_lazy_import(filename):
  File "/pfs/work7/workspace/scratch/ma_mkacar-team_project_fss2024/miniconda3/envs/py310/lib/python3.8/site-packages/mmengine/config/config.py", line 1661, in _is_lazy_import
    with open(filename, encoding='utf-8') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/pfs/work7/workspace/scratch/ma_mkacar-team_project_fss2024/benchmarking_robustness/semantic_segmentation/corruptions/corruption_config/pascalvoc/mask2former/./mask2former_r50_8xb2-160k_voc12aug-512x512.py'
Finished processing corruption type: glass_blur
Processing corruption type: motion_blur
Traceback (most recent call last):
  File "tools/test.py", line 123, in <module>
    main()
  File "tools/test.py", line 86, in main
    cfg = Config.fromfile(args.config)
  File "/pfs/work7/workspace/scratch/ma_mkacar-team_project_fss2024/miniconda3/envs/py310/lib/python3.8/site-packages/mmengine/config/config.py", line 461, in fromfile
    cfg_dict, cfg_text, env_variables = Config._file2dict(
  File "/pfs/work7/workspace/scratch/ma_mkacar-team_project_fss2024/miniconda3/envs/py310/lib/python3.8/site-packages/mmengine/config/config.py", line 947, in _file2dict
    raise e
  File "/pfs/work7/workspace/scratch/ma_mkacar-team_project_fss2024/miniconda3/envs/py310/lib/python3.8/site-packages/mmengine/config/config.py", line 889, in _file2dict
    _cfg_dict, _cfg_text, _env_variables = Config._file2dict(
  File "/pfs/work7/workspace/scratch/ma_mkacar-team_project_fss2024/miniconda3/envs/py310/lib/python3.8/site-packages/mmengine/config/config.py", line 947, in _file2dict
    raise e
  File "/pfs/work7/workspace/scratch/ma_mkacar-team_project_fss2024/miniconda3/envs/py310/lib/python3.8/site-packages/mmengine/config/config.py", line 889, in _file2dict
    _cfg_dict, _cfg_text, _env_variables = Config._file2dict(
  File "/pfs/work7/workspace/scratch/ma_mkacar-team_project_fss2024/miniconda3/envs/py310/lib/python3.8/site-packages/mmengine/config/config.py", line 845, in _file2dict
    if lazy_import is None and Config._is_lazy_import(filename):
  File "/pfs/work7/workspace/scratch/ma_mkacar-team_project_fss2024/miniconda3/envs/py310/lib/python3.8/site-packages/mmengine/config/config.py", line 1661, in _is_lazy_import
    with open(filename, encoding='utf-8') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/pfs/work7/workspace/scratch/ma_mkacar-team_project_fss2024/benchmarking_robustness/semantic_segmentation/corruptions/corruption_config/pascalvoc/mask2former/./mask2former_r50_8xb2-160k_voc12aug-512x512.py'
Finished processing corruption type: motion_blur
Processing corruption type: zoom_blur
Traceback (most recent call last):
  File "tools/test.py", line 123, in <module>
    main()
  File "tools/test.py", line 86, in main
    cfg = Config.fromfile(args.config)
  File "/pfs/work7/workspace/scratch/ma_mkacar-team_project_fss2024/miniconda3/envs/py310/lib/python3.8/site-packages/mmengine/config/config.py", line 461, in fromfile
    cfg_dict, cfg_text, env_variables = Config._file2dict(
  File "/pfs/work7/workspace/scratch/ma_mkacar-team_project_fss2024/miniconda3/envs/py310/lib/python3.8/site-packages/mmengine/config/config.py", line 947, in _file2dict
    raise e
  File "/pfs/work7/workspace/scratch/ma_mkacar-team_project_fss2024/miniconda3/envs/py310/lib/python3.8/site-packages/mmengine/config/config.py", line 889, in _file2dict
    _cfg_dict, _cfg_text, _env_variables = Config._file2dict(
  File "/pfs/work7/workspace/scratch/ma_mkacar-team_project_fss2024/miniconda3/envs/py310/lib/python3.8/site-packages/mmengine/config/config.py", line 947, in _file2dict
    raise e
  File "/pfs/work7/workspace/scratch/ma_mkacar-team_project_fss2024/miniconda3/envs/py310/lib/python3.8/site-packages/mmengine/config/config.py", line 889, in _file2dict
    _cfg_dict, _cfg_text, _env_variables = Config._file2dict(
  File "/pfs/work7/workspace/scratch/ma_mkacar-team_project_fss2024/miniconda3/envs/py310/lib/python3.8/site-packages/mmengine/config/config.py", line 845, in _file2dict
    if lazy_import is None and Config._is_lazy_import(filename):
  File "/pfs/work7/workspace/scratch/ma_mkacar-team_project_fss2024/miniconda3/envs/py310/lib/python3.8/site-packages/mmengine/config/config.py", line 1661, in _is_lazy_import
    with open(filename, encoding='utf-8') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/pfs/work7/workspace/scratch/ma_mkacar-team_project_fss2024/benchmarking_robustness/semantic_segmentation/corruptions/corruption_config/pascalvoc/mask2former/./mask2former_r50_8xb2-160k_voc12aug-512x512.py'
Finished processing corruption type: zoom_blur
Processing corruption type: snow
Traceback (most recent call last):
  File "tools/test.py", line 123, in <module>
    main()
  File "tools/test.py", line 86, in main
    cfg = Config.fromfile(args.config)
  File "/pfs/work7/workspace/scratch/ma_mkacar-team_project_fss2024/miniconda3/envs/py310/lib/python3.8/site-packages/mmengine/config/config.py", line 461, in fromfile
    cfg_dict, cfg_text, env_variables = Config._file2dict(
  File "/pfs/work7/workspace/scratch/ma_mkacar-team_project_fss2024/miniconda3/envs/py310/lib/python3.8/site-packages/mmengine/config/config.py", line 947, in _file2dict
    raise e
  File "/pfs/work7/workspace/scratch/ma_mkacar-team_project_fss2024/miniconda3/envs/py310/lib/python3.8/site-packages/mmengine/config/config.py", line 889, in _file2dict
    _cfg_dict, _cfg_text, _env_variables = Config._file2dict(
  File "/pfs/work7/workspace/scratch/ma_mkacar-team_project_fss2024/miniconda3/envs/py310/lib/python3.8/site-packages/mmengine/config/config.py", line 947, in _file2dict
    raise e
  File "/pfs/work7/workspace/scratch/ma_mkacar-team_project_fss2024/miniconda3/envs/py310/lib/python3.8/site-packages/mmengine/config/config.py", line 889, in _file2dict
    _cfg_dict, _cfg_text, _env_variables = Config._file2dict(
  File "/pfs/work7/workspace/scratch/ma_mkacar-team_project_fss2024/miniconda3/envs/py310/lib/python3.8/site-packages/mmengine/config/config.py", line 845, in _file2dict
    if lazy_import is None and Config._is_lazy_import(filename):
  File "/pfs/work7/workspace/scratch/ma_mkacar-team_project_fss2024/miniconda3/envs/py310/lib/python3.8/site-packages/mmengine/config/config.py", line 1661, in _is_lazy_import
    with open(filename, encoding='utf-8') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/pfs/work7/workspace/scratch/ma_mkacar-team_project_fss2024/benchmarking_robustness/semantic_segmentation/corruptions/corruption_config/pascalvoc/mask2former/./mask2former_r50_8xb2-160k_voc12aug-512x512.py'
Finished processing corruption type: snow
Processing corruption type: frost
Traceback (most recent call last):
  File "tools/test.py", line 123, in <module>
    main()
  File "tools/test.py", line 86, in main
    cfg = Config.fromfile(args.config)
  File "/pfs/work7/workspace/scratch/ma_mkacar-team_project_fss2024/miniconda3/envs/py310/lib/python3.8/site-packages/mmengine/config/config.py", line 461, in fromfile
    cfg_dict, cfg_text, env_variables = Config._file2dict(
  File "/pfs/work7/workspace/scratch/ma_mkacar-team_project_fss2024/miniconda3/envs/py310/lib/python3.8/site-packages/mmengine/config/config.py", line 947, in _file2dict
    raise e
  File "/pfs/work7/workspace/scratch/ma_mkacar-team_project_fss2024/miniconda3/envs/py310/lib/python3.8/site-packages/mmengine/config/config.py", line 889, in _file2dict
    _cfg_dict, _cfg_text, _env_variables = Config._file2dict(
  File "/pfs/work7/workspace/scratch/ma_mkacar-team_project_fss2024/miniconda3/envs/py310/lib/python3.8/site-packages/mmengine/config/config.py", line 947, in _file2dict
    raise e
  File "/pfs/work7/workspace/scratch/ma_mkacar-team_project_fss2024/miniconda3/envs/py310/lib/python3.8/site-packages/mmengine/config/config.py", line 889, in _file2dict
    _cfg_dict, _cfg_text, _env_variables = Config._file2dict(
  File "/pfs/work7/workspace/scratch/ma_mkacar-team_project_fss2024/miniconda3/envs/py310/lib/python3.8/site-packages/mmengine/config/config.py", line 845, in _file2dict
    if lazy_import is None and Config._is_lazy_import(filename):
  File "/pfs/work7/workspace/scratch/ma_mkacar-team_project_fss2024/miniconda3/envs/py310/lib/python3.8/site-packages/mmengine/config/config.py", line 1661, in _is_lazy_import
    with open(filename, encoding='utf-8') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/pfs/work7/workspace/scratch/ma_mkacar-team_project_fss2024/benchmarking_robustness/semantic_segmentation/corruptions/corruption_config/pascalvoc/mask2former/./mask2former_r50_8xb2-160k_voc12aug-512x512.py'
Finished processing corruption type: frost
Processing corruption type: fog
Traceback (most recent call last):
  File "tools/test.py", line 123, in <module>
    main()
  File "tools/test.py", line 86, in main
    cfg = Config.fromfile(args.config)
  File "/pfs/work7/workspace/scratch/ma_mkacar-team_project_fss2024/miniconda3/envs/py310/lib/python3.8/site-packages/mmengine/config/config.py", line 461, in fromfile
    cfg_dict, cfg_text, env_variables = Config._file2dict(
  File "/pfs/work7/workspace/scratch/ma_mkacar-team_project_fss2024/miniconda3/envs/py310/lib/python3.8/site-packages/mmengine/config/config.py", line 947, in _file2dict
    raise e
  File "/pfs/work7/workspace/scratch/ma_mkacar-team_project_fss2024/miniconda3/envs/py310/lib/python3.8/site-packages/mmengine/config/config.py", line 889, in _file2dict
    _cfg_dict, _cfg_text, _env_variables = Config._file2dict(
  File "/pfs/work7/workspace/scratch/ma_mkacar-team_project_fss2024/miniconda3/envs/py310/lib/python3.8/site-packages/mmengine/config/config.py", line 947, in _file2dict
    raise e
  File "/pfs/work7/workspace/scratch/ma_mkacar-team_project_fss2024/miniconda3/envs/py310/lib/python3.8/site-packages/mmengine/config/config.py", line 889, in _file2dict
    _cfg_dict, _cfg_text, _env_variables = Config._file2dict(
  File "/pfs/work7/workspace/scratch/ma_mkacar-team_project_fss2024/miniconda3/envs/py310/lib/python3.8/site-packages/mmengine/config/config.py", line 845, in _file2dict
    if lazy_import is None and Config._is_lazy_import(filename):
  File "/pfs/work7/workspace/scratch/ma_mkacar-team_project_fss2024/miniconda3/envs/py310/lib/python3.8/site-packages/mmengine/config/config.py", line 1661, in _is_lazy_import
    with open(filename, encoding='utf-8') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/pfs/work7/workspace/scratch/ma_mkacar-team_project_fss2024/benchmarking_robustness/semantic_segmentation/corruptions/corruption_config/pascalvoc/mask2former/./mask2former_r50_8xb2-160k_voc12aug-512x512.py'
Finished processing corruption type: fog
Processing corruption type: brightness
Traceback (most recent call last):
  File "tools/test.py", line 123, in <module>
    main()
  File "tools/test.py", line 86, in main
    cfg = Config.fromfile(args.config)
  File "/pfs/work7/workspace/scratch/ma_mkacar-team_project_fss2024/miniconda3/envs/py310/lib/python3.8/site-packages/mmengine/config/config.py", line 461, in fromfile
    cfg_dict, cfg_text, env_variables = Config._file2dict(
  File "/pfs/work7/workspace/scratch/ma_mkacar-team_project_fss2024/miniconda3/envs/py310/lib/python3.8/site-packages/mmengine/config/config.py", line 947, in _file2dict
    raise e
  File "/pfs/work7/workspace/scratch/ma_mkacar-team_project_fss2024/miniconda3/envs/py310/lib/python3.8/site-packages/mmengine/config/config.py", line 889, in _file2dict
    _cfg_dict, _cfg_text, _env_variables = Config._file2dict(
  File "/pfs/work7/workspace/scratch/ma_mkacar-team_project_fss2024/miniconda3/envs/py310/lib/python3.8/site-packages/mmengine/config/config.py", line 947, in _file2dict
    raise e
  File "/pfs/work7/workspace/scratch/ma_mkacar-team_project_fss2024/miniconda3/envs/py310/lib/python3.8/site-packages/mmengine/config/config.py", line 889, in _file2dict
    _cfg_dict, _cfg_text, _env_variables = Config._file2dict(
  File "/pfs/work7/workspace/scratch/ma_mkacar-team_project_fss2024/miniconda3/envs/py310/lib/python3.8/site-packages/mmengine/config/config.py", line 845, in _file2dict
    if lazy_import is None and Config._is_lazy_import(filename):
  File "/pfs/work7/workspace/scratch/ma_mkacar-team_project_fss2024/miniconda3/envs/py310/lib/python3.8/site-packages/mmengine/config/config.py", line 1661, in _is_lazy_import
    with open(filename, encoding='utf-8') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/pfs/work7/workspace/scratch/ma_mkacar-team_project_fss2024/benchmarking_robustness/semantic_segmentation/corruptions/corruption_config/pascalvoc/mask2former/./mask2former_r50_8xb2-160k_voc12aug-512x512.py'
Finished processing corruption type: brightness
Processing corruption type: contrast
Traceback (most recent call last):
  File "tools/test.py", line 123, in <module>
    main()
  File "tools/test.py", line 86, in main
    cfg = Config.fromfile(args.config)
  File "/pfs/work7/workspace/scratch/ma_mkacar-team_project_fss2024/miniconda3/envs/py310/lib/python3.8/site-packages/mmengine/config/config.py", line 461, in fromfile
    cfg_dict, cfg_text, env_variables = Config._file2dict(
  File "/pfs/work7/workspace/scratch/ma_mkacar-team_project_fss2024/miniconda3/envs/py310/lib/python3.8/site-packages/mmengine/config/config.py", line 947, in _file2dict
    raise e
  File "/pfs/work7/workspace/scratch/ma_mkacar-team_project_fss2024/miniconda3/envs/py310/lib/python3.8/site-packages/mmengine/config/config.py", line 889, in _file2dict
    _cfg_dict, _cfg_text, _env_variables = Config._file2dict(
  File "/pfs/work7/workspace/scratch/ma_mkacar-team_project_fss2024/miniconda3/envs/py310/lib/python3.8/site-packages/mmengine/config/config.py", line 947, in _file2dict
    raise e
  File "/pfs/work7/workspace/scratch/ma_mkacar-team_project_fss2024/miniconda3/envs/py310/lib/python3.8/site-packages/mmengine/config/config.py", line 889, in _file2dict
    _cfg_dict, _cfg_text, _env_variables = Config._file2dict(
  File "/pfs/work7/workspace/scratch/ma_mkacar-team_project_fss2024/miniconda3/envs/py310/lib/python3.8/site-packages/mmengine/config/config.py", line 845, in _file2dict
    if lazy_import is None and Config._is_lazy_import(filename):
  File "/pfs/work7/workspace/scratch/ma_mkacar-team_project_fss2024/miniconda3/envs/py310/lib/python3.8/site-packages/mmengine/config/config.py", line 1661, in _is_lazy_import
    with open(filename, encoding='utf-8') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/pfs/work7/workspace/scratch/ma_mkacar-team_project_fss2024/benchmarking_robustness/semantic_segmentation/corruptions/corruption_config/pascalvoc/mask2former/./mask2former_r50_8xb2-160k_voc12aug-512x512.py'
Finished processing corruption type: contrast
Processing corruption type: elastic_transform
Traceback (most recent call last):
  File "tools/test.py", line 123, in <module>
    main()
  File "tools/test.py", line 86, in main
    cfg = Config.fromfile(args.config)
  File "/pfs/work7/workspace/scratch/ma_mkacar-team_project_fss2024/miniconda3/envs/py310/lib/python3.8/site-packages/mmengine/config/config.py", line 461, in fromfile
    cfg_dict, cfg_text, env_variables = Config._file2dict(
  File "/pfs/work7/workspace/scratch/ma_mkacar-team_project_fss2024/miniconda3/envs/py310/lib/python3.8/site-packages/mmengine/config/config.py", line 947, in _file2dict
    raise e
  File "/pfs/work7/workspace/scratch/ma_mkacar-team_project_fss2024/miniconda3/envs/py310/lib/python3.8/site-packages/mmengine/config/config.py", line 889, in _file2dict
    _cfg_dict, _cfg_text, _env_variables = Config._file2dict(
  File "/pfs/work7/workspace/scratch/ma_mkacar-team_project_fss2024/miniconda3/envs/py310/lib/python3.8/site-packages/mmengine/config/config.py", line 947, in _file2dict
    raise e
  File "/pfs/work7/workspace/scratch/ma_mkacar-team_project_fss2024/miniconda3/envs/py310/lib/python3.8/site-packages/mmengine/config/config.py", line 889, in _file2dict
    _cfg_dict, _cfg_text, _env_variables = Config._file2dict(
  File "/pfs/work7/workspace/scratch/ma_mkacar-team_project_fss2024/miniconda3/envs/py310/lib/python3.8/site-packages/mmengine/config/config.py", line 845, in _file2dict
    if lazy_import is None and Config._is_lazy_import(filename):
  File "/pfs/work7/workspace/scratch/ma_mkacar-team_project_fss2024/miniconda3/envs/py310/lib/python3.8/site-packages/mmengine/config/config.py", line 1661, in _is_lazy_import
    with open(filename, encoding='utf-8') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/pfs/work7/workspace/scratch/ma_mkacar-team_project_fss2024/benchmarking_robustness/semantic_segmentation/corruptions/corruption_config/pascalvoc/mask2former/./mask2former_r50_8xb2-160k_voc12aug-512x512.py'
Finished processing corruption type: elastic_transform
Processing corruption type: pixelate
Traceback (most recent call last):
  File "tools/test.py", line 123, in <module>
    main()
  File "tools/test.py", line 86, in main
    cfg = Config.fromfile(args.config)
  File "/pfs/work7/workspace/scratch/ma_mkacar-team_project_fss2024/miniconda3/envs/py310/lib/python3.8/site-packages/mmengine/config/config.py", line 461, in fromfile
    cfg_dict, cfg_text, env_variables = Config._file2dict(
  File "/pfs/work7/workspace/scratch/ma_mkacar-team_project_fss2024/miniconda3/envs/py310/lib/python3.8/site-packages/mmengine/config/config.py", line 947, in _file2dict
    raise e
  File "/pfs/work7/workspace/scratch/ma_mkacar-team_project_fss2024/miniconda3/envs/py310/lib/python3.8/site-packages/mmengine/config/config.py", line 889, in _file2dict
    _cfg_dict, _cfg_text, _env_variables = Config._file2dict(
  File "/pfs/work7/workspace/scratch/ma_mkacar-team_project_fss2024/miniconda3/envs/py310/lib/python3.8/site-packages/mmengine/config/config.py", line 947, in _file2dict
    raise e
  File "/pfs/work7/workspace/scratch/ma_mkacar-team_project_fss2024/miniconda3/envs/py310/lib/python3.8/site-packages/mmengine/config/config.py", line 889, in _file2dict
    _cfg_dict, _cfg_text, _env_variables = Config._file2dict(
  File "/pfs/work7/workspace/scratch/ma_mkacar-team_project_fss2024/miniconda3/envs/py310/lib/python3.8/site-packages/mmengine/config/config.py", line 845, in _file2dict
    if lazy_import is None and Config._is_lazy_import(filename):
  File "/pfs/work7/workspace/scratch/ma_mkacar-team_project_fss2024/miniconda3/envs/py310/lib/python3.8/site-packages/mmengine/config/config.py", line 1661, in _is_lazy_import
    with open(filename, encoding='utf-8') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/pfs/work7/workspace/scratch/ma_mkacar-team_project_fss2024/benchmarking_robustness/semantic_segmentation/corruptions/corruption_config/pascalvoc/mask2former/./mask2former_r50_8xb2-160k_voc12aug-512x512.py'
Finished processing corruption type: pixelate
Processing corruption type: jpeg_compression
Traceback (most recent call last):
  File "tools/test.py", line 123, in <module>
    main()
  File "tools/test.py", line 86, in main
    cfg = Config.fromfile(args.config)
  File "/pfs/work7/workspace/scratch/ma_mkacar-team_project_fss2024/miniconda3/envs/py310/lib/python3.8/site-packages/mmengine/config/config.py", line 461, in fromfile
    cfg_dict, cfg_text, env_variables = Config._file2dict(
  File "/pfs/work7/workspace/scratch/ma_mkacar-team_project_fss2024/miniconda3/envs/py310/lib/python3.8/site-packages/mmengine/config/config.py", line 947, in _file2dict
    raise e
  File "/pfs/work7/workspace/scratch/ma_mkacar-team_project_fss2024/miniconda3/envs/py310/lib/python3.8/site-packages/mmengine/config/config.py", line 889, in _file2dict
    _cfg_dict, _cfg_text, _env_variables = Config._file2dict(
  File "/pfs/work7/workspace/scratch/ma_mkacar-team_project_fss2024/miniconda3/envs/py310/lib/python3.8/site-packages/mmengine/config/config.py", line 947, in _file2dict
    raise e
  File "/pfs/work7/workspace/scratch/ma_mkacar-team_project_fss2024/miniconda3/envs/py310/lib/python3.8/site-packages/mmengine/config/config.py", line 889, in _file2dict
    _cfg_dict, _cfg_text, _env_variables = Config._file2dict(
  File "/pfs/work7/workspace/scratch/ma_mkacar-team_project_fss2024/miniconda3/envs/py310/lib/python3.8/site-packages/mmengine/config/config.py", line 845, in _file2dict
    if lazy_import is None and Config._is_lazy_import(filename):
  File "/pfs/work7/workspace/scratch/ma_mkacar-team_project_fss2024/miniconda3/envs/py310/lib/python3.8/site-packages/mmengine/config/config.py", line 1661, in _is_lazy_import
    with open(filename, encoding='utf-8') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/pfs/work7/workspace/scratch/ma_mkacar-team_project_fss2024/benchmarking_robustness/semantic_segmentation/corruptions/corruption_config/pascalvoc/mask2former/./mask2former_r50_8xb2-160k_voc12aug-512x512.py'
Finished processing corruption type: jpeg_compression
Processing corruption type: elastic_transform
Traceback (most recent call last):
  File "tools/test.py", line 123, in <module>
    main()
  File "tools/test.py", line 86, in main
    cfg = Config.fromfile(args.config)
  File "/pfs/work7/workspace/scratch/ma_mkacar-team_project_fss2024/miniconda3/envs/py310/lib/python3.8/site-packages/mmengine/config/config.py", line 461, in fromfile
    cfg_dict, cfg_text, env_variables = Config._file2dict(
  File "/pfs/work7/workspace/scratch/ma_mkacar-team_project_fss2024/miniconda3/envs/py310/lib/python3.8/site-packages/mmengine/config/config.py", line 947, in _file2dict
    raise e
  File "/pfs/work7/workspace/scratch/ma_mkacar-team_project_fss2024/miniconda3/envs/py310/lib/python3.8/site-packages/mmengine/config/config.py", line 889, in _file2dict
    _cfg_dict, _cfg_text, _env_variables = Config._file2dict(
  File "/pfs/work7/workspace/scratch/ma_mkacar-team_project_fss2024/miniconda3/envs/py310/lib/python3.8/site-packages/mmengine/config/config.py", line 947, in _file2dict
    raise e
  File "/pfs/work7/workspace/scratch/ma_mkacar-team_project_fss2024/miniconda3/envs/py310/lib/python3.8/site-packages/mmengine/config/config.py", line 889, in _file2dict
    _cfg_dict, _cfg_text, _env_variables = Config._file2dict(
  File "/pfs/work7/workspace/scratch/ma_mkacar-team_project_fss2024/miniconda3/envs/py310/lib/python3.8/site-packages/mmengine/config/config.py", line 845, in _file2dict
    if lazy_import is None and Config._is_lazy_import(filename):
  File "/pfs/work7/workspace/scratch/ma_mkacar-team_project_fss2024/miniconda3/envs/py310/lib/python3.8/site-packages/mmengine/config/config.py", line 1661, in _is_lazy_import
    with open(filename, encoding='utf-8') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/pfs/work7/workspace/scratch/ma_mkacar-team_project_fss2024/benchmarking_robustness/semantic_segmentation/corruptions/corruption_config/pascalvoc/mask2former/./mask2former_r50_8xb2-160k_voc12aug-512x512.py'
Finished processing corruption type: elastic_transform
Processing corruption type: pixelate
Traceback (most recent call last):
  File "tools/test.py", line 123, in <module>
    main()
  File "tools/test.py", line 86, in main
    cfg = Config.fromfile(args.config)
  File "/pfs/work7/workspace/scratch/ma_mkacar-team_project_fss2024/miniconda3/envs/py310/lib/python3.8/site-packages/mmengine/config/config.py", line 461, in fromfile
    cfg_dict, cfg_text, env_variables = Config._file2dict(
  File "/pfs/work7/workspace/scratch/ma_mkacar-team_project_fss2024/miniconda3/envs/py310/lib/python3.8/site-packages/mmengine/config/config.py", line 947, in _file2dict
    raise e
  File "/pfs/work7/workspace/scratch/ma_mkacar-team_project_fss2024/miniconda3/envs/py310/lib/python3.8/site-packages/mmengine/config/config.py", line 889, in _file2dict
    _cfg_dict, _cfg_text, _env_variables = Config._file2dict(
  File "/pfs/work7/workspace/scratch/ma_mkacar-team_project_fss2024/miniconda3/envs/py310/lib/python3.8/site-packages/mmengine/config/config.py", line 947, in _file2dict
    raise e
  File "/pfs/work7/workspace/scratch/ma_mkacar-team_project_fss2024/miniconda3/envs/py310/lib/python3.8/site-packages/mmengine/config/config.py", line 889, in _file2dict
    _cfg_dict, _cfg_text, _env_variables = Config._file2dict(
  File "/pfs/work7/workspace/scratch/ma_mkacar-team_project_fss2024/miniconda3/envs/py310/lib/python3.8/site-packages/mmengine/config/config.py", line 845, in _file2dict
    if lazy_import is None and Config._is_lazy_import(filename):
  File "/pfs/work7/workspace/scratch/ma_mkacar-team_project_fss2024/miniconda3/envs/py310/lib/python3.8/site-packages/mmengine/config/config.py", line 1661, in _is_lazy_import
    with open(filename, encoding='utf-8') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/pfs/work7/workspace/scratch/ma_mkacar-team_project_fss2024/benchmarking_robustness/semantic_segmentation/corruptions/corruption_config/pascalvoc/mask2former/./mask2former_r50_8xb2-160k_voc12aug-512x512.py'
Finished processing corruption type: pixelate
Processing corruption type: jpeg_compression
Traceback (most recent call last):
  File "tools/test.py", line 123, in <module>
    main()
  File "tools/test.py", line 86, in main
    cfg = Config.fromfile(args.config)
  File "/pfs/work7/workspace/scratch/ma_mkacar-team_project_fss2024/miniconda3/envs/py310/lib/python3.8/site-packages/mmengine/config/config.py", line 461, in fromfile
    cfg_dict, cfg_text, env_variables = Config._file2dict(
  File "/pfs/work7/workspace/scratch/ma_mkacar-team_project_fss2024/miniconda3/envs/py310/lib/python3.8/site-packages/mmengine/config/config.py", line 947, in _file2dict
    raise e
  File "/pfs/work7/workspace/scratch/ma_mkacar-team_project_fss2024/miniconda3/envs/py310/lib/python3.8/site-packages/mmengine/config/config.py", line 889, in _file2dict
    _cfg_dict, _cfg_text, _env_variables = Config._file2dict(
  File "/pfs/work7/workspace/scratch/ma_mkacar-team_project_fss2024/miniconda3/envs/py310/lib/python3.8/site-packages/mmengine/config/config.py", line 947, in _file2dict
    raise e
  File "/pfs/work7/workspace/scratch/ma_mkacar-team_project_fss2024/miniconda3/envs/py310/lib/python3.8/site-packages/mmengine/config/config.py", line 889, in _file2dict
    _cfg_dict, _cfg_text, _env_variables = Config._file2dict(
  File "/pfs/work7/workspace/scratch/ma_mkacar-team_project_fss2024/miniconda3/envs/py310/lib/python3.8/site-packages/mmengine/config/config.py", line 845, in _file2dict
    if lazy_import is None and Config._is_lazy_import(filename):
  File "/pfs/work7/workspace/scratch/ma_mkacar-team_project_fss2024/miniconda3/envs/py310/lib/python3.8/site-packages/mmengine/config/config.py", line 1661, in _is_lazy_import
    with open(filename, encoding='utf-8') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/pfs/work7/workspace/scratch/ma_mkacar-team_project_fss2024/benchmarking_robustness/semantic_segmentation/corruptions/corruption_config/pascalvoc/mask2former/./mask2former_r50_8xb2-160k_voc12aug-512x512.py'
Finished processing corruption type: jpeg_compression
Runtime: 1731645523

============================= JOB FEEDBACK =============================

NodeName=uc2n487
Job ID: 24674780
Cluster: uc2
User/Group: ma_mkacar/ma_ma
State: COMPLETED (exit code 0)
Nodes: 1
Cores per node: 6
CPU Utilized: 00:00:33
CPU Efficiency: 5.05% of 00:10:54 core-walltime
Job Wall-clock time: 00:01:49
Memory Utilized: 247.21 MB
Memory Efficiency: 2.41% of 10.00 GB
